#!/usr/bin/env python3
"""Synthetic-only POSIX, exact-environment, and Modal persistence canary.

This program never opens the reproduction input archive or invokes a scientific
runner. The only exported payload is 4096 newly generated bytes and metadata.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import signal
import stat
import subprocess
import sys
import tempfile

from supervisor import (
    canonical_transport_path, canonical_volume_root, check_posix, digest,
    modal_commit, now, scientific_environment, write_json,
)

PAYLOAD_SIZE = 4096
PACKAGES = {
    "huggingface_hub": "1.29.0", "matplotlib": "3.11.1", "numpy": "2.4.6",
    "pandas": "3.0.5", "scikit-learn": "1.9.0", "scipy": "1.17.1",
    "sentence-transformers": "6.0.0", "torch": "2.13.0", "transformers": "5.16.1",
    "jsonschema": "4.26.0",
}
PREFIX = Path("/persist/durable-rerun-20260920/storage-canaries")


def exact_environment(job):
    code = (
        "import importlib.metadata as m,json,platform; "
        f"names={list(PACKAGES)!r}; "
        "print(json.dumps({'python':platform.python_version(),'packages':{k:m.version(k) for k in names}},sort_keys=True))"
    )
    result = subprocess.run(
        ["/opt/stopdff-env/bin/python", "-I", "-c", code],
        env=scientific_environment(job), stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
        timeout=60, check=False,
    )
    if result.returncode != 0 or len(result.stdout) > 16384:
        raise RuntimeError("Exact scientific environment check failed")
    record = json.loads(result.stdout)
    if record != {"python": "3.11.12", "packages": PACKAGES}:
        raise ValueError("Exact scientific environment mismatch")
    return record


def synthetic_files(durable, run_id, image_id, volume_id, posix, environment, commit_mode):
    """Create the sole data payload and its bounded identity record."""
    payload = os.urandom(PAYLOAD_SIZE)
    target = durable / "synthetic.bin"
    with target.open("xb") as stream:
        stream.write(payload)
        stream.flush()
        os.fchmod(stream.fileno(), 0o751)
        os.fsync(stream.fileno())
    if target.read_bytes() != payload or stat.S_IMODE(target.stat().st_mode) != 0o751:
        raise ValueError("Synthetic mounted-volume bytes or executable mode mismatch")
    record = {
        "schema_version": 1, "status": "SYNTHETIC_DATA_WRITTEN", "run_id": run_id,
        "image_id": image_id, "volume_id": volume_id, "storage_canary_sha256": digest(Path(__file__)),
        "supervisor_sha256": digest(Path(__file__).with_name("supervisor.py")),
        "created_utc": now(), "commit_mode": commit_mode, "posix": posix,
        "environment": environment, "research_data_accessed": False,
        "scientific_execution_performed": False, "scientific_acceptance": False,
        "payload": {"path": "synthetic.bin", "size": len(payload),
                    "sha256": hashlib.sha256(payload).hexdigest(), "mode": 0o751},
    }
    write_json(durable / "payload.json", record, exclusive=True)
    return record


def deadline(_number, _frame):
    raise TimeoutError("Synthetic canary bounded deadline")


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-id", required=True)
    parser.add_argument("--image-id", required=True)
    parser.add_argument("--volume-name", default="cs321m-stopdff-rerun-20260920-v2")
    parser.add_argument("--volume-id", required=True)
    parser.add_argument("--commit-mode", choices=("sdk", "sync-v2"), default="sdk")
    args = parser.parse_args(argv)
    if not re.fullmatch(r"[a-z0-9][a-z0-9._-]{0,47}", args.run_id):
        parser.error("Invalid synthetic run ID")
    if not re.fullmatch(r"im-[A-Za-z0-9]+", args.image_id):
        parser.error("Invalid image ID")
    if args.volume_name != "cs321m-stopdff-rerun-20260920-v2":
        parser.error("Unexpected volume")
    signal.signal(signal.SIGALRM, deadline)
    signal.alarm(540)
    stage = "initialize"
    try:
        mount = Path("/persist")
        root = canonical_volume_root(mount, args.volume_id)
        durable = canonical_transport_path(PREFIX / args.run_id, mount, root)
        durable.mkdir(parents=True, exist_ok=True)
        write_json(durable / "started.json", {
            "schema_version": 1, "run_id": args.run_id, "image_id": args.image_id,
            "volume_id": args.volume_id, "scope": "synthetic-only", "started_utc": now(),
        }, exclusive=True)
        with tempfile.TemporaryDirectory(prefix="stopdff-storage-canary-") as local:
            job = Path(local)
            for name in ("home", "tmp"):
                (job / name).mkdir()
            stage = "local_posix"
            posix = check_posix(job)
            stage = "exact_environment"
            environment = exact_environment(job)
            stage = "write_synthetic"
            record = synthetic_files(durable, args.run_id, args.image_id, args.volume_id,
                                     posix, environment, args.commit_mode)
            stage = "explicit_payload_commit"
            modal_commit(args.commit_mode, args.volume_name, Path("/persist"))
            stage = "completion_receipt"
            completion = {
                **record, "status": "STORAGE_CANARY_PASSED", "explicit_payload_commit_succeeded": True,
                "completed_utc": now(), "payload_receipt": {
                    "path": "payload.json", "sha256": digest(durable / "payload.json"),
                    "size": (durable / "payload.json").stat().st_size,
                },
            }
            write_json(durable / "completion.json", completion, exclusive=True)
            stage = "explicit_completion_commit"
            modal_commit(args.commit_mode, args.volume_name, Path("/persist"))
        print(json.dumps({"schema_version": 1, "run_id": args.run_id, "status": "STORAGE_CANARY_PASSED",
                          "scientific_acceptance": False, "exported_data_bytes": PAYLOAD_SIZE}), flush=True)
        return 0
    except BaseException as exc:
        # Never print exceptions, subprocess output, environment, or SDK diagnostics.
        print(json.dumps({"schema_version": 1, "run_id": args.run_id, "status": "STORAGE_CANARY_FAILED",
                          "stage": stage, "error_type": type(exc).__name__, "scientific_acceptance": False}), flush=True)
        return 1
    finally:
        signal.alarm(0)


if __name__ == "__main__":
    raise SystemExit(main())
